### ISSUE TITLE
span span span span

### ISSUE THREAD

**Issue by TrevorBramble** [sinatra/sinatra.github.com#122]
Somehow I'm screwing this up. When I go to update the docs to take into account a change in the reloader library, its page has all this extra markup in it now.

My commit seems innocent. https://github.com/sinatra/sinatra-contrib/commit/49808befdb43d7b66fcf16f3cae05c423e1e8705

Any ideas?

``` diff
-<h1>Sinatra::Reloader</h1>
+<h1 id="label-Sinatra%3A%3AReloader">Sinatra::Reloader<span><a href="#label-Sinatra%3A%3AReloader">&para;</a> <a href="#documentation">&uarr;</a></span></h1>
```

![image](https://f.cloud.github.com/assets/92880/1649894/1b0b49ec-5a41-11e3-900d-05fb1da0e353.png)

**Comment by zzak** [comment]
This is something I think we have to fix upstream in RDoc.

Current implementation just adds these links automatically, or you can change their appearance.

There is no autoshow/hide effect currently, something like how Github renders headings on README documents.

I think we can add to a future release of RDoc (and use that version when building our docs). Until then, I will leave this ticket open for reference.

**Comment by zzak** [comment]
I think this issue was fixed upstream from us because I can't reproduce it now
