### ISSUE TITLE
Chris Schneider’s Blog: GITTR

### ISSUE THREAD

**Issue by vis-kid** [sinatra/sinatra.github.com#194]
Under `/documentation`, the link to this blog is dead…

Should I delete it?

**Comment by zzak** [comment]
There's actually [sinatra/sinatra-book](https://github.com/sinatra/sinatra-book) that we should incorporate into the site build process.

**Comment by vis-kid** [comment]
cool!

**Comment by olleolleolle** [comment]
The gittr.com link has been excised in #246 - this Issue can now be closed.

Thanks for caring about the documentation, folks!
