### ISSUE TITLE
Wild page contains broken links

### ISSUE THREAD

**Issue by CharlyJazz** [sinatra/sinatra.github.com#231]
On the page http://www.sinatrarb.com/wild.html there are broken links

**In Applications:**

[OnBoard](http://dev.vemarsas.it/onboard/)
[Tweeps](http://tweeps.webdirections.org/)
[Rank Captain](http://rankcaptain.com/)
[SumaApp](http://sumapp.com/)

**In Websites:** 

[Bloor and Lansdowne is Blansdowne ](http://blansdowne.ca/)  **Server Error**
[NYLS Upload Tool](http://upload.citylaw.org/)
[Calendar About Nothing](http://calendaraboutnothing.com/)
[Congrelate](http://congrelate.com/)
[SavvyFranchises](http://www.savvyfranchises.com/)
[happens.co.za](http://www.happens.co.za/)
[Ant genome database](http://fourmidable.unil.ch/)
[Goodnot.es](http://Goodnot.es)

**Comment by zzak** [comment]
@CharlyJazz  I think we should move these to something like "alumni" section and just list the name w/o a link.
