### ISSUE TITLE
Can't access Sinatra website

### ISSUE THREAD

**Issue by meisyal** [sinatra/sinatra.github.com#232]
I try to access Sinatra website, http://sinatrarb.com. My browser (Mozilla Firefox 57.0) tells me that the website is not redirecting properly. The same issue happens when I access https://sinatra.github.io. I can't confirm this issue just happened to me or others.

This issue didn't happen when I accessed the website two days ago or so. Maybe this changes afdb5416d8e02232747228cd8466142ffe33cca6 affects the website or domain configuration.

**Comment by kgrz** [comment]
@meisyal Pushed a temporary mirror to sinatra.wtf

**Comment by zzak** [comment]
Aaaaand we're back! http://sinatrarb.com/

**Comment by meisyal** [comment]
Thank you guys
