### ISSUE TITLE
enable HTTPS

### ISSUE THREAD

**Issue by FranklinYu** [sinatra/sinatra.github.com#243]
It’s free: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

**Comment by FranklinYu** [comment]
Any news?

**Comment by rmoriz** [comment]
To enable https, the DNS zone of sinatrarb.com needs to be updated to point to github's "new" pages endpoints as noted in https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by hickford** [comment]
> All GitHub Pages sites, including sites that are correctly configured with a custom domain, support HTTPS and HTTPS enforcement.

https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

http://sinatrarb.com/

**Comment by jkowens** [comment]
Done 🎉
