### ISSUE TITLE
Anchor in documentation

### ISSUE THREAD

**Issue by FranklinYu** [sinatra/sinatra.github.com#248]
It would be great if I can link to sections in http://sinatrarb.com/intro.html with anchors, such as http://sinatrarb.com/intro.html#return-values.

**Comment by anaschwendler** [comment]
I can try this one 👋

**Comment by Deer-Spangle** [comment]
I was just thinking this today too. @anaschwendler Did you get a chance to add that?

**Comment by anaschwendler** [comment]
Hello @Deer-Spangle!
No I didn't worked in it because I didn't know very well how to contribute the right way 🤔 

Feel free to take over!
